title: Media Server
theme: dark
color: slate
headerStyle: clean
layout:
  Media:
    style: row
    columns: 4
  Downloads:
    style: row
    columns: 3
  System:
    style: row
    columns: 3
  Photos:
    style: row
    columns: 2
